name: Frontend CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]  

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Jest Unit Tests
        run: npm test

      - name: Build Next.js App
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook -- --output-dir=storybook-static
