name: Frontend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start backend server (json-server)
        run: |
          cd backend
          node server.js &
      
      - name: Wait for backend
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:8000
          timeout: 30

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npx jest --config=jest.config.js --passWithNoTests

      - name: Build Next.js App
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook -- --output-dir=storybook-static

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --only-changed --exit-zero-on-changes

      - name: Manually test login
        run: |
          curl -X POST http://localhost:8000/login \
          -H "Content-Type: application/json" \
          -d '{"email":"test@test.com", "password":"1234"}'

      - name: Run Cypress E2E
        run: npm run e2e
