name: Frontend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Start backend server
        working-directory: backend
        run: npm run start &

      - name: Wait for backend
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:8000
          timeout: 30

      - name: Run Lint
        working-directory: frontend
        run: npm run lint

      - name: Run Unit Tests
        working-directory: frontend
        run: npm run test

      - name: Build Next.js App
        working-directory: frontend
        run: npm run build

      - name: Build Storybook
        working-directory: frontend
        run: npm run build-storybook -- --output-dir=storybook-static

      - name: Publish to Chromatic
        working-directory: frontend
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --only-changed --exit-zero-on-changes

      - name: Run Cypress E2E
        working-directory: frontend
        run: npm run e2e
