name: Frontend CI

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]  

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npx jest --config=jest.config.js --passWithNoTests

      - name: Build Next.js App
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook -- --output-dir=storybook-static

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
